name: romstools-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - numpy>2,<2.3
  # testing
  - zarr<3
  - pytest
  - pytest-xdist
  - h5py
  - flake8
  - black
  - pre-commit==3.8.0
  - coverage
