name: romstools-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - sphinx
  - nbsphinx
  - sphinx-book-theme
  - sphinxcontrib-bibtex
  - pre-commit==3.8.0
  # for running jupyter notebooks
  - ipykernel
